name: v_card_qr_code
description: "Project do generate QrCode of Vcard data."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6    
  qr_flutter: ^4.0.0
  vcard_maintained: ^0.0.1+1
  shared_preferences: ^2.0.6
  permission_handler: ^10.0.0
  contacts_service: ^0.6.3
  flutter_contacts: ^1.1.8
  shimmer: ^3.0.0
  flutter_multi_formatter: ^2.1.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#243443"
  image: assets/images/splash_screen.jpeg
  
  android_12:
    color: "#243443"
    icon_background_color: "#243443"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpeg"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
